
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 01 01:13:15 CET 2011
//----------------------------------------------------

package calcul.analyseurs;

/** CUP generated class containing symbol constants. */
public class TypeSymboles {
  /* terminals */
  public static final int MINUS = 8;
  public static final int DIVIDE = 10;
  public static final int NUMBER = 11;
  public static final int VARIABLE = 3;
  public static final int EOF = 0;
  public static final int PLUS = 7;
  public static final int PARENTHESISR = 6;
  public static final int error = 1;
  public static final int UNAIRE = 12;
  public static final int TIMES = 9;
  public static final int AFFECTATIONCST = 4;
  public static final int END = 2;
  public static final int PARENTHESISL = 5;
}

