
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 10 10:46:10 CET 2011
//----------------------------------------------------

package init.analyseurs;

/** CUP generated class containing symbol constants. */
public class TypeSymboles {
  /* terminals */
  public static final int READ = 5;
  public static final int IDENT = 2;
  public static final int SEPVAR = 9;
  public static final int PROG = 3;
  public static final int EOF = 0;
  public static final int DECLINT = 4;
  public static final int DECLLIST = 12;
  public static final int FININSTR = 8;
  public static final int ENTIER = 6;
  public static final int FIN_LISTE = 11;
  public static final int error = 1;
  public static final int AFF = 7;
  public static final int DEBUT_LISTE = 10;
}

